remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Tech Community Consulting
description: Tech Community Consulting Ltd. is an organisation set up by Adam Jackson to help the tech industry build connections with their communities.
show_downloads: false
google_analytics: G-LVZLZVPD77
